# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tasarim.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(832, 578)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 841, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_daire = QtWidgets.QWidget()
        self.tab_daire.setObjectName("tab_daire")
        self.lbl_circle = QtWidgets.QLabel(self.tab_daire)
        self.lbl_circle.setGeometry(QtCore.QRect(30, 70, 771, 351))
        self.lbl_circle.setAutoFillBackground(True)
        self.lbl_circle.setText("")
        self.lbl_circle.setObjectName("lbl_circle")
        self.btn_draw = QtWidgets.QPushButton(self.tab_daire)
        self.btn_draw.setGeometry(QtCore.QRect(30, 30, 75, 23))
        self.btn_draw.setObjectName("btn_draw")
        self.line_width = QtWidgets.QLineEdit(self.tab_daire)
        self.line_width.setGeometry(QtCore.QRect(230, 30, 113, 20))
        self.line_width.setObjectName("line_width")
        self.line_height = QtWidgets.QLineEdit(self.tab_daire)
        self.line_height.setGeometry(QtCore.QRect(420, 30, 113, 20))
        self.line_height.setObjectName("line_height")
        self.label_8 = QtWidgets.QLabel(self.tab_daire)
        self.label_8.setGeometry(QtCore.QRect(180, 30, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_daire)
        self.label_9.setGeometry(QtCore.QRect(370, 30, 47, 13))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_daire, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btn_rotateLeft = QtWidgets.QPushButton(self.tab)
        self.btn_rotateLeft.setGeometry(QtCore.QRect(250, 20, 75, 23))
        self.btn_rotateLeft.setObjectName("btn_rotateLeft")
        self.lbl_rotate = QtWidgets.QLabel(self.tab)
        self.lbl_rotate.setGeometry(QtCore.QRect(80, 60, 661, 411))
        self.lbl_rotate.setText("")
        self.lbl_rotate.setObjectName("lbl_rotate")
        self.btn_rotateRight = QtWidgets.QPushButton(self.tab)
        self.btn_rotateRight.setGeometry(QtCore.QRect(430, 20, 75, 23))
        self.btn_rotateRight.setObjectName("btn_rotateRight")
        self.btn_rotate_addPic = QtWidgets.QPushButton(self.tab)
        self.btn_rotate_addPic.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.btn_rotate_addPic.setObjectName("btn_rotate_addPic")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.txt_height = QtWidgets.QLineEdit(self.tab_2)
        self.txt_height.setGeometry(QtCore.QRect(160, 30, 113, 20))
        self.txt_height.setObjectName("txt_height")
        self.txt_width = QtWidgets.QLineEdit(self.tab_2)
        self.txt_width.setGeometry(QtCore.QRect(410, 30, 113, 20))
        self.txt_width.setObjectName("txt_width")
        self.btn_resize = QtWidgets.QPushButton(self.tab_2)
        self.btn_resize.setGeometry(QtCore.QRect(560, 30, 75, 23))
        self.btn_resize.setObjectName("btn_resize")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(110, 30, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(360, 30, 47, 13))
        self.label_7.setObjectName("label_7")
        self.lbl_resize = QtWidgets.QLabel(self.tab_2)
        self.lbl_resize.setGeometry(QtCore.QRect(110, 90, 551, 311))
        self.lbl_resize.setText("")
        self.lbl_resize.setObjectName("lbl_resize")
        self.btn_resizeAddPic = QtWidgets.QPushButton(self.tab_2)
        self.btn_resizeAddPic.setGeometry(QtCore.QRect(20, 30, 75, 23))
        self.btn_resizeAddPic.setObjectName("btn_resizeAddPic")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_filtre = QtWidgets.QWidget()
        self.tab_filtre.setObjectName("tab_filtre")
        self.btn_image_filter_add = QtWidgets.QPushButton(self.tab_filtre)
        self.btn_image_filter_add.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.btn_image_filter_add.setObjectName("btn_image_filter_add")
        self.lbl_original = QtWidgets.QLabel(self.tab_filtre)
        self.lbl_original.setGeometry(QtCore.QRect(20, 60, 341, 351))
        self.lbl_original.setAutoFillBackground(True)
        self.lbl_original.setText("")
        self.lbl_original.setObjectName("lbl_original")
        self.radio_gray = QtWidgets.QRadioButton(self.tab_filtre)
        self.radio_gray.setGeometry(QtCore.QRect(110, 20, 82, 17))
        self.radio_gray.setObjectName("radio_gray")
        self.radio_binary = QtWidgets.QRadioButton(self.tab_filtre)
        self.radio_binary.setGeometry(QtCore.QRect(190, 20, 82, 17))
        self.radio_binary.setObjectName("radio_binary")
        self.radio_zero = QtWidgets.QRadioButton(self.tab_filtre)
        self.radio_zero.setGeometry(QtCore.QRect(250, 20, 51, 17))
        self.radio_zero.setObjectName("radio_zero")
        self.radio_otzu = QtWidgets.QRadioButton(self.tab_filtre)
        self.radio_otzu.setGeometry(QtCore.QRect(300, 20, 82, 17))
        self.radio_otzu.setObjectName("radio_otzu")
        self.lbl_filtre_image = QtWidgets.QLabel(self.tab_filtre)
        self.lbl_filtre_image.setGeometry(QtCore.QRect(440, 60, 341, 351))
        self.lbl_filtre_image.setAutoFillBackground(True)
        self.lbl_filtre_image.setText("")
        self.lbl_filtre_image.setObjectName("lbl_filtre_image")
        self.radio_histogram = QtWidgets.QRadioButton(self.tab_filtre)
        self.radio_histogram.setGeometry(QtCore.QRect(360, 20, 82, 17))
        self.radio_histogram.setObjectName("radio_histogram")
        self.radio_clahe = QtWidgets.QRadioButton(self.tab_filtre)
        self.radio_clahe.setGeometry(QtCore.QRect(430, 20, 82, 17))
        self.radio_clahe.setObjectName("radio_clahe")
        self.tabWidget.addTab(self.tab_filtre, "")
        self.tab_mantiksal = QtWidgets.QWidget()
        self.tab_mantiksal.setObjectName("tab_mantiksal")
        self.lbl_image1 = QtWidgets.QLabel(self.tab_mantiksal)
        self.lbl_image1.setGeometry(QtCore.QRect(10, 20, 291, 221))
        self.lbl_image1.setAutoFillBackground(True)
        self.lbl_image1.setText("")
        self.lbl_image1.setObjectName("lbl_image1")
        self.lbl_image2 = QtWidgets.QLabel(self.tab_mantiksal)
        self.lbl_image2.setGeometry(QtCore.QRect(350, 20, 291, 221))
        self.lbl_image2.setAutoFillBackground(True)
        self.lbl_image2.setText("")
        self.lbl_image2.setObjectName("lbl_image2")
        self.lbl_image_result = QtWidgets.QLabel(self.tab_mantiksal)
        self.lbl_image_result.setGeometry(QtCore.QRect(190, 300, 291, 201))
        self.lbl_image_result.setAutoFillBackground(True)
        self.lbl_image_result.setText("")
        self.lbl_image_result.setObjectName("lbl_image_result")
        self.btn_image1_add = QtWidgets.QPushButton(self.tab_mantiksal)
        self.btn_image1_add.setGeometry(QtCore.QRect(100, 260, 75, 23))
        self.btn_image1_add.setObjectName("btn_image1_add")
        self.btn_image2_add = QtWidgets.QPushButton(self.tab_mantiksal)
        self.btn_image2_add.setGeometry(QtCore.QRect(460, 260, 75, 23))
        self.btn_image2_add.setObjectName("btn_image2_add")
        self.combo_logic = QtWidgets.QComboBox(self.tab_mantiksal)
        self.combo_logic.setGeometry(QtCore.QRect(630, 260, 101, 22))
        self.combo_logic.setObjectName("combo_logic")
        self.combo_logic.addItem("")
        self.combo_logic.addItem("")
        self.combo_logic.addItem("")
        self.combo_logic.addItem("")
        self.btn_apply = QtWidgets.QPushButton(self.tab_mantiksal)
        self.btn_apply.setGeometry(QtCore.QRect(740, 260, 75, 23))
        self.btn_apply.setObjectName("btn_apply")
        self.tabWidget.addTab(self.tab_mantiksal, "")
        self.tab_lable = QtWidgets.QWidget()
        self.tab_lable.setObjectName("tab_lable")
        self.lbl_image_lable = QtWidgets.QLabel(self.tab_lable)
        self.lbl_image_lable.setGeometry(QtCore.QRect(30, 50, 351, 191))
        self.lbl_image_lable.setAutoFillBackground(True)
        self.lbl_image_lable.setText("")
        self.lbl_image_lable.setObjectName("lbl_image_lable")
        self.lbl_image_detect = QtWidgets.QLabel(self.tab_lable)
        self.lbl_image_detect.setGeometry(QtCore.QRect(430, 50, 371, 401))
        self.lbl_image_detect.setAutoFillBackground(True)
        self.lbl_image_detect.setText("")
        self.lbl_image_detect.setObjectName("lbl_image_detect")
        self.btn_original_image_add = QtWidgets.QPushButton(self.tab_lable)
        self.btn_original_image_add.setGeometry(QtCore.QRect(170, 250, 75, 23))
        self.btn_original_image_add.setObjectName("btn_original_image_add")
        self.btn_lableling = QtWidgets.QPushButton(self.tab_lable)
        self.btn_lableling.setGeometry(QtCore.QRect(570, 470, 75, 23))
        self.btn_lableling.setObjectName("btn_lableling")
        self.label = QtWidgets.QLabel(self.tab_lable)
        self.label.setGeometry(QtCore.QRect(30, 20, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_lable)
        self.label_2.setGeometry(QtCore.QRect(430, 20, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.tab_lable)
        self.label_5.setGeometry(QtCore.QRect(30, 250, 81, 16))
        self.label_5.setObjectName("label_5")
        self.btn_searching_image_add = QtWidgets.QPushButton(self.tab_lable)
        self.btn_searching_image_add.setGeometry(QtCore.QRect(170, 490, 75, 23))
        self.btn_searching_image_add.setObjectName("btn_searching_image_add")
        self.lbl_image_lable_2 = QtWidgets.QLabel(self.tab_lable)
        self.lbl_image_lable_2.setGeometry(QtCore.QRect(30, 280, 351, 191))
        self.lbl_image_lable_2.setAutoFillBackground(True)
        self.lbl_image_lable_2.setText("")
        self.lbl_image_lable_2.setObjectName("lbl_image_lable_2")
        self.tabWidget.addTab(self.tab_lable, "")
        self.tab_gurultu = QtWidgets.QWidget()
        self.tab_gurultu.setObjectName("tab_gurultu")
        self.label_3 = QtWidgets.QLabel(self.tab_gurultu)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 81, 16))
        self.label_3.setObjectName("label_3")
        self.btn_addImage_Noisy = QtWidgets.QPushButton(self.tab_gurultu)
        self.btn_addImage_Noisy.setGeometry(QtCore.QRect(170, 430, 75, 23))
        self.btn_addImage_Noisy.setObjectName("btn_addImage_Noisy")
        self.lbl_image_Orginal = QtWidgets.QLabel(self.tab_gurultu)
        self.lbl_image_Orginal.setGeometry(QtCore.QRect(40, 50, 351, 361))
        self.lbl_image_Orginal.setAutoFillBackground(True)
        self.lbl_image_Orginal.setText("")
        self.lbl_image_Orginal.setObjectName("lbl_image_Orginal")
        self.label_4 = QtWidgets.QLabel(self.tab_gurultu)
        self.label_4.setGeometry(QtCore.QRect(440, 20, 81, 16))
        self.label_4.setObjectName("label_4")
        self.btn_noisy = QtWidgets.QPushButton(self.tab_gurultu)
        self.btn_noisy.setGeometry(QtCore.QRect(570, 430, 75, 23))
        self.btn_noisy.setObjectName("btn_noisy")
        self.lbl_image_noisy = QtWidgets.QLabel(self.tab_gurultu)
        self.lbl_image_noisy.setGeometry(QtCore.QRect(440, 50, 371, 361))
        self.lbl_image_noisy.setAutoFillBackground(True)
        self.lbl_image_noisy.setText("")
        self.lbl_image_noisy.setObjectName("lbl_image_noisy")
        self.tabWidget.addTab(self.tab_gurultu, "")
        self.btn_close = QtWidgets.QPushButton(Form)
        self.btn_close.setGeometry(QtCore.QRect(390, 550, 75, 23))
        self.btn_close.setObjectName("btn_close")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_draw.setText(_translate("Form", "Draw"))
        self.label_8.setText(_translate("Form", "Width:"))
        self.label_9.setText(_translate("Form", "Height:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_daire), _translate("Form", "Draw Circle"))
        self.btn_rotateLeft.setText(_translate("Form", "Rotate Left"))
        self.btn_rotateRight.setText(_translate("Form", "Rotate Right"))
        self.btn_rotate_addPic.setText(_translate("Form", "Add Picture"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Rotation"))
        self.btn_resize.setText(_translate("Form", "Resize"))
        self.label_6.setText(_translate("Form", "Height:"))
        self.label_7.setText(_translate("Form", "Width"))
        self.btn_resizeAddPic.setText(_translate("Form", "Add Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Resize"))
        self.btn_image_filter_add.setText(_translate("Form", "Add Image"))
        self.radio_gray.setText(_translate("Form", "Gray Scale"))
        self.radio_binary.setText(_translate("Form", "Binary"))
        self.radio_zero.setText(_translate("Form", "Zero"))
        self.radio_otzu.setText(_translate("Form", "OTZU"))
        self.radio_histogram.setText(_translate("Form", "Histogram"))
        self.radio_clahe.setText(_translate("Form", "Clahe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_filtre), _translate("Form", "Modify"))
        self.btn_image1_add.setText(_translate("Form", "Add Image1"))
        self.btn_image2_add.setText(_translate("Form", "Add Image2"))
        self.combo_logic.setItemText(0, _translate("Form", "OR"))
        self.combo_logic.setItemText(1, _translate("Form", "AND"))
        self.combo_logic.setItemText(2, _translate("Form", "NOT"))
        self.combo_logic.setItemText(3, _translate("Form", "XOR"))
        self.btn_apply.setText(_translate("Form", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mantiksal), _translate("Form", "Logical"))
        self.btn_original_image_add.setText(_translate("Form", "Image1 Add"))
        self.btn_lableling.setText(_translate("Form", "Lableling"))
        self.label.setText(_translate("Form", "Orginal Image"))
        self.label_2.setText(_translate("Form", "Lableling"))
        self.label_5.setText(_translate("Form", "Detected Image"))
        self.btn_searching_image_add.setText(_translate("Form", "Image2 Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_lable), _translate("Form", "Lableling"))
        self.label_3.setText(_translate("Form", "Orginal Image"))
        self.btn_addImage_Noisy.setText(_translate("Form", "Add Image"))
        self.label_4.setText(_translate("Form", "Noisy Image"))
        self.btn_noisy.setText(_translate("Form", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_gurultu), _translate("Form", "Noisy"))
        self.btn_close.setText(_translate("Form", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

